language: objective-c

osx_image: xcode8.2

# restrict branch push jobs to pushes to master branch; PRs will still build every push
branches:
  only: 
    - master

before_install:
  - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get stable --auto-dotfiles
    
install: bundle install && bundle exec pod install

script:
  - xcodebuild clean test -workspace Atlas.xcworkspace -scheme Atlas -destination 'id=DB794781-65A7-4884-8D00-AAC3CBD39A44' -configuration Debug
  - xcodebuild clean test -workspace Atlas.xcworkspace -scheme Programmatic -destination 'id=DB794781-65A7-4884-8D00-AAC3CBD39A44' -configuration Debug
  - xcodebuild clean test -workspace Atlas.xcworkspace -scheme Storyboard -destination 'id=DB794781-65A7-4884-8D00-AAC3CBD39A44' -configuration Debug
